server:
  port: 8080

spring:
  application:
    name: tdd-basic

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show-sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          fetch_size: 500
          batch_versioned_data: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tdd;MODE=MYSQL;
    username: sa
    password:

  flyway:
    url: jdbc:h2:mem:tdd
    user: sa
    password:
    baseline-on-migrate: true

  h2:
    console:
      enabled: true
      path: /h2-console

